name: Testing actions

on:
  push:
    branches: [main]
  pull_request:
    types:
      - opened
      - closed
      - reopened
      - assigned

jobs:
  simple-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: list files
        run: ls
      - name: Echo a string
        run: echo "Hello World"
      - name: multiline
        run: |
          echo "line 1"
          echo "Line 2"
      - name: no newline
        run: >
          echo "Line 3
          and line 4"
      - name: Checkout to Vm
        uses: actions/checkout@v1
      - name: list files after Checkout
        run: ls

  simple-windows:
    runs-on: windows-latest
    steps:
      - name: Run a shell command
        run: pwd
        shell: bash
      - name: powershell command
        run: get-location
