name: Test yaml files

on:
  push:
    branches: [main]

jobs:
  test-windows:
    runs-on: windows-latest
    needs: running-on-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2
