name: Test yaml files

on:
  push:
    branches: [main]

jobs:
  without-need:
    runs-on: windows-latest
    steps:
      - run: echo "before needs"
  test-windows:
    runs-on: windows-latest
    needs: running-on-windows
    steps:
      - name: Checkout
        uses: actions/checkout@v2
