name: Test dependency

on:
  workflow_run:
    workflows: ["Testing actions"]
    types:
      - requested
    # - completed

jobs:
  independent:
    runs-on: windows-latest
    steps:
      - run: echo "before needs"
  dependent:
    runs-on: windows-latest
    needs: independent
    steps:
      - name: Checkout
        uses: actions/checkout@v2
