name: Test yaml files

on:
  workflow_run:
    workflows: [Testing actions]
    types:
      - completed

jobs:
  without-need:
    runs-on: windows-latest
    steps:
      - run: echo "before needs"
  test-windows:
    runs-on: windows-latest
    needs: without-need
    steps:
      - name: Checkout
        uses: actions/checkout@v2
